spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false


logging:
  level:
    root: info
    com.kwok: debug
  file:
    name: blog-dev.log
    path: mylog/
server:
  port: 8086

#整合mybatis
mybatis:
  type-aliases-package: com.kwok.pojo
  mapper-locations: classpath:mapper/*.xml
